### ISSUE TITLE
lb_target_group not compatible with aws_lb of type network

### ISSUE THREAD

**Issue by fawzyj** [terraform-providers/terraform-provider-aws#1912]
Using AWS provider 1.1

I cannot create lb_target_goup for aws_lb of type "network"
I want to create a network load balancer to balance some tcp connection, but when i set the aws_lb_target_group protocol to 'tcp' I got the following error: 

> aws_lb_target_group.tg: "protocol" must be either "HTTP" or "HTTPS"

The code:

```
resource "aws_lb" "ecs_lb" {
  name            = "ecs-lb"
  load_balancer_type = "network"
  subnets         = ["${aws_subnet.public.*.id}"]
  security_groups = ["${aws_security_group.lb_sg.id}"]
}

resource "aws_lb_target_group" "application_tg" {
  name     = "application_tg"
  port     = 80
  protocol = "tcp"
  vpc_id   = "${aws_vpc.main.id}"
}
```

**Comment by briankohler** [comment]
This should be marked as a bug.  It makes network load balancers unusable, and I can only assume it's supposed to be a working feature since it's referenced in the documentation.

**Comment by rrueth** [comment]
I'm seeing the same error as @fawzyj. I agree with @briankohler that this should be a bug. Without being able to create the TCP target group, you cannot create a complete Network Load Balancer in Terraform.

**Comment by aandriyc** [comment]
+1 same issue, and this is also true for health checks, as it gives this error:
"health_check.0.protocol" must be either "HTTP" or "HTTPS"

**Comment by ccovarru** [comment]
+1 Confirming issue as well.

**Comment by Ginja** [comment]
Should be addressed by #1884

**Comment by code4mankind** [comment]
+1 Definitely a **bug**, not an enhancement - aws_lb of type "network" is unusable, unable to create aws_lb_listener with "TCP" protocol.

**Comment by aandriyc** [comment]
Looks like there are more changes needed. Even if you build AWS provider with the changes above (#1884), NLB resource still fails with this message:
Failure Setting ALB Subnets: InvalidConfigurationRequest: SetSubnets is not supported for load balancers of type 'network'
	status code: 400, request id: 4c173a71-b36c-11e7-9ffb-4f8e5bd294fa
Note though, that NLB is created anyway and looks valid. And further Terraform plan / apply shows everything as up to date.

Trying to create NLB with subnet_mapping blocks instead of subnets list just hangs indefinitely

**Comment by joseph-holland** [comment]
Yes, more changes are required.  I had opened a duplicate issue by accident (#1944).

- [AWS Network LB API docs ](http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html)specify that HTTP, HTTPS or TCP protocols are accepted values: 
> Protocol
>    The protocol to use for routing traffic to the targets. For Application Load Balancers, the supported protocols are HTTP and HTTPS. For Network Load Balancers, the supported protocol is TCP.
>    Type: String
>    Valid Values: HTTP | HTTPS | TCP
>    Required: Yes

- [resource_aws_lb_target_group.go](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_lb_target_group.go)
Saw when checking the source that even though the new Network LBs are supported the code to check the protocol was not updated. This also seems to be the case with the health check code too.
```
421 func validateAwsLbTargetGroupProtocol(v interface{}, k string) (ws []string, errors []error) {
422  	protocol := strings.ToLower(v.(string))
423  	if protocol == "http" || protocol == "https" {
424  		return
425  	}
426  
427  	errors = append(errors, fmt.Errorf("%q must be either %q or %q", k, "HTTP", "HTTPS"))
428  	return
429  }
```

**Comment by briankohler** [comment]
Not sure if this should be covered too, but NLBs (and maybe ALBs, I'm not sure off the top of my head) can now accept either an IP address or an InstanceID as targets.  I've confirmed that doesn't work on on any branches, and it seems that feature is not trivial to incorporate.

**Comment by bploetz** [comment]
I'm not sure if this is related or not, but the `aws_lb` Data Source doesn't seem to work with Network Load Balancers either.

I created two load balancers manually in the AWS console: one Network Load Balancer, one Application Load Balancer. When I try to reference the Network Load Balancer in an `aws_lb` Data Source, I get this error:

```
data "aws_lb" "test" {
  arn = "arn:aws:elasticloadbalancing:us-west-2:XXXXXXXXXX:loadbalancer/net/test/XXXXXXXXXXX"
}
```

terraform plan:
```
Error refreshing state: 1 error(s) occurred:

* module.aws_test.data.aws_lb.test: 1 error(s) occurred:

* module.aws_test.data.aws_lb.test: data.aws_lb.test: Error retrieving LB: LoadBalancerNotFound: One or more load balancers not found
	status code: 400, request id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

However when I plug in the ARN of the Application Load Balancer to the `aws_lb` Data Source, it works just fine.

I can obviously split this into a separate issue if need be, just let me know.

**Comment by korjik** [comment]
I don't think that SetSubnets issue was resolved in any mentioned issues above. The error is mentioned, but I don't see any fixes for this exact problem.

When using config:

```hcl
resource "aws_lb" "nlb" {
  name                = "${var.nlb_name}"
  load_balancer_type  = "network"
  internal            = true
  subnets             = ["${var.subnet_ids}"]
}
```
We receive:
```
* aws_lb.nlb: Failure Setting ALB Subnets: InvalidConfigurationRequest: SetSubnets is not supported for load balancers of type 'network'
	status code: 400, request id: 6fbf4ef2-b8d6-11e7-a30b-cd396b848124
```
`subnets` is a valid method for create-load-balancer type `network`: http://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancer-cli.html

**Comment by zihaoyu** [comment]
Not only is the `protocol` field of `aws_lb_target_group` resource affected, but also the `health_check` protocol. I'm seeing two errors with my Network LB with TCP healthcheck:

```
* module.my_module.aws_lb_target_group.master: "health_check.0.protocol" must be either "HTTP" or "HTTPS"
* module.my_module.aws_lb_target_group.master: "protocol" must be either "HTTP" or "HTTPS"
```

**Comment by OferE** [comment]
Using aws version 1.2 - this problem still remains.
Network load balancer are not usable because of it.
This is critical - when can we expect this fix?

**Comment by farvour** [comment]
@OferE the worst part is it clearly wasn't even tested, because setting a target attachment would have failed immediately since NLBs only support HTTP/HTTPS protocols as far as I know. Even worse it made it to the Terraform documentation. This is definitely a blocker for using this feature.

**Comment by mminks** [comment]
+1

**Comment by fterrier** [comment]
+1

**Comment by Gephorian** [comment]
+1

**Comment by nvenky** [comment]
+1

**Comment by Ehekatl** [comment]
@radeksimko can you mark this as bug? It's been long time since the nlb support released, but it's completely broken. There are some pending fixes already: #1884

**Comment by akafrmn** [comment]
+1

**Comment by Skewled** [comment]
+1
